### ISSUE TITLE
Eureka Overlay not pulling/displaying locally edited map in Hydatos

### ISSUE THREAD

**Issue by Tess-McBoots** [quisquous/cactbot#4239]
## Description

I've edited the Eureka overlay files locally to also have the bunny coffer locations on them. They're loading fine in Pagos and Pyros! But Hydatos isn't loading the edited image (attached).

## Additional information

If available, please include any logs or screenshots depicting the issue you're experiencing.
![hydatos](https://user-images.githubusercontent.com/96307114/162499477-b7bb9b1e-9b12-4659-8bf2-8df22f00a1d0.png)

**Comment by quisquous** [comment]
For whatever reason, it looks like the hydatos map gets bundled by webpack as part of the build process, and so its image source is just a base64 encoded file, but the other maps do not.  (I looked at this via "open devtools" to look at the element when in different zones.)  It's not clear to me why, as they are all loaded the same way.  However, editing these files directly is not generally going to be a reliable way to keep things up to date, as this bundling may change in the future.

Your best bet is this.  In your cactbot user folder, create a file called "eureka.css" and then add this:
```css
.aspect-ratio-pyros > .inner-container > img {
  content: url("pyros_custom.png");
}
.aspect-ratio-pagos > .inner-container > img {
  content: url("pagos_custom.png");
}
.aspect-ratio-hydatos > .inner-container > img {
  content: url("hydatos_custom.png");
}
```

Rename your custom images to `pagos_custom.png` and put them next to the `pagos.png` that comes with cactbot.  This will replace the images with your custom ones.
